### ISSUE TITLE
使用脚本安装成功，但之前的firewalld中配置的转发forward都失效了

### ISSUE THREAD

**Issue by jiachaosun** [paniy/Xray_bash_onekey#4]
```
public
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh dhcpv6-client
  ports: 80/tcp 443/tcp 34579/tcp 34579/udp 27607/tcp 34580/tcp 34580/udp 11111/tcp
  protocols: 
  masquerade: yes
  forward-ports: port=34579:proto=tcp:toport=443:toaddr=xxx
        port=34579:proto=udp:toport=443:toaddr=xxx
        port=34580:proto=tcp:toport=443:toaddr=xxx
        port=34580:proto=udp:toport=443:toaddr=xxx
  source-ports: 
  icmp-blocks: 
  rich rules:
```

原来都是可用的，但是用了你的脚本后这块就失败了是什么原因呀？
